In [1]:
import pandas

In [2]:
df = pandas.read_csv("resume_data.csv",encoding='utf-8-sig')

In [3]:
df.head()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [4]:
df.columns

Index(['address', 'career_objective', 'skills', 'educational_institution_name',
       'degree_names', 'passing_years', 'educational_results', 'result_types',
       'major_field_of_studies', 'professional_company_names', 'company_urls',
       'start_dates', 'end_dates', 'related_skils_in_job', 'positions',
       'locations', 'responsibilities', 'extra_curricular_activity_types',
       'extra_curricular_organization_names',
       'extra_curricular_organization_links', 'role_positions', 'languages',
       'proficiency_levels', 'certification_providers', 'certification_skills',
       'online_links', 'issue_dates', 'expiry_dates', '﻿job_position_name',
       'educationaL_requirements', 'experiencere_requirement',
       'age_requirement', 'responsibilities.1', 'skills_required',
       'matched_score'],
      dtype='object')

In [5]:
df.drop(["address","educational_results","result_types", "company_urls","extra_curricular_organization_links", "online_links"], axis=1, inplace=True)

In [6]:
df.head()

,career_objective,skills,educational_institution_name,degree_names,passing_years,major_field_of_studies,professional_company_names,start_dates,end_dates,related_skils_in_job,...,certification_skills,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['Electronics'],['Coca-COla'],['Nov 2019'],['Till Date'],[['Big Data']],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['Mathematics', 'Statistics']",['BIB Consultancy'],['Sep 2019'],['Till Date'],"[['Data Analysis', 'Business Analysis', 'Machi...",...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['Electronics/Telecommunication'],['Axis Bank Limited'],['June 2018'],['Till Date'],"[['Unified Payment Interface', 'Risk Predictio...",...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...","['January 2011', 'January 2008', 'January 2006...","['November 2015', 'January 2010', 'January 200...","[['accounts receivables', 'banking', 'G/L Acco...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...","['January 2016', 'January 2016', 'January 2012...","['Current', 'January 2016', 'January 2015', 'J...","[['collections', 'accounts receivable', 'finan...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [7]:
df.drop(["issue_dates"	,"expiry_dates"], axis=1, inplace=True)

In [8]:
df.head()

,career_objective,skills,educational_institution_name,degree_names,passing_years,major_field_of_studies,professional_company_names,start_dates,end_dates,related_skils_in_job,...,proficiency_levels,certification_providers,certification_skills,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['Electronics'],['Coca-COla'],['Nov 2019'],['Till Date'],[['Big Data']],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['Mathematics', 'Statistics']",['BIB Consultancy'],['Sep 2019'],['Till Date'],"[['Data Analysis', 'Business Analysis', 'Machi...",...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['Electronics/Telecommunication'],['Axis Bank Limited'],['June 2018'],['Till Date'],"[['Unified Payment Interface', 'Risk Predictio...",...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...","['January 2011', 'January 2008', 'January 2006...","['November 2015', 'January 2010', 'January 200...","[['accounts receivables', 'banking', 'G/L Acco...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...","['January 2016', 'January 2016', 'January 2012...","['Current', 'January 2016', 'January 2015', 'J...","[['collections', 'accounts receivable', 'finan...",...,NaN,['Ohio Notary Public'],[None],Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [9]:
df.columns

Index(['career_objective', 'skills', 'educational_institution_name',
       'degree_names', 'passing_years', 'major_field_of_studies',
       'professional_company_names', 'start_dates', 'end_dates',
       'related_skils_in_job', 'positions', 'locations', 'responsibilities',
       'extra_curricular_activity_types',
       'extra_curricular_organization_names', 'role_positions', 'languages',
       'proficiency_levels', 'certification_providers', 'certification_skills',
       '﻿job_position_name', 'educationaL_requirements',
       'experiencere_requirement', 'age_requirement', 'responsibilities.1',
       'skills_required', 'matched_score'],
      dtype='object')

In [10]:
df["passing_years"] = df["passing_years"].apply(lambda x: f"Passing Year: {x}")
df["degree_names"] = df["degree_names"].apply(lambda x: f"degree names: {x}")
df["age_requirement"] = df["age_requirement"].apply(lambda x: f"age requirement: {x}")
df["responsibilities.1"] = df["responsibilities.1"].apply(lambda x: f"responsibilities : {x}")

In [11]:
df.head()

,career_objective,skills,educational_institution_name,degree_names,passing_years,major_field_of_studies,professional_company_names,start_dates,end_dates,related_skils_in_job,...,proficiency_levels,certification_providers,certification_skills,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,degree names: ['B.Tech'],Passing Year: ['2019'],['Electronics'],['Coca-COla'],['Nov 2019'],['Till Date'],[['Big Data']],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,age requirement: nan,responsibilities : Technical Support\nTroubles...,NaN,0.850000
1,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","degree names: ['B.Sc (Maths)', 'M.Sc (Science)...","Passing Year: ['2015', '2018']","['Mathematics', 'Statistics']",['BIB Consultancy'],['Sep 2019'],['Till Date'],"[['Data Analysis', 'Business Analysis', 'Machi...",...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),age requirement: nan,responsibilities : Machine Learning Leadership...,NaN,0.750000
2,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",degree names: ['B.Tech'],Passing Year: ['2018'],['Electronics/Telecommunication'],['Axis Bank Limited'],['June 2018'],['Till Date'],"[['Unified Payment Interface', 'Risk Predictio...",...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,age requirement: nan,responsibilities : Trade Marketing Executive\n...,Brand Promotion\nCampaign Management\nField Su...,0.416667
3,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",degree names: ['Computer Applications Speciali...,Passing Year: ['2008'],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...","['January 2011', 'January 2008', 'January 2006...","['November 2015', 'January 2010', 'January 200...","[['accounts receivables', 'banking', 'G/L Acco...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,age requirement: Age 22 to 30 years,responsibilities : Apparel Sourcing\nQuality G...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],degree names: ['Bachelor of Business Administr...,Passing Year: [None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...","['January 2016', 'January 2016', 'January 2012...","['Current', 'January 2016', 'January 2015', 'J...","[['collections', 'accounts receivable', 'finan...",...,NaN,['Ohio Notary Public'],[None],Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,age requirement: nan,responsibilities : iOS Lifecycle\nRequirement ...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [12]:
resume_cols = [
    'career_objective', 'skills', 'educational_institution_name',
    'degree_names', 'passing_years', 'major_field_of_studies',
    'professional_company_names', 'start_dates', 'end_dates',
    'related_skils_in_job', 'positions', 'locations', 'responsibilities',
    'extra_curricular_activity_types', 'extra_curricular_organization_names',
    'role_positions', 'languages', 'proficiency_levels',
    'certification_providers', 'certification_skills'
]

jd_cols = [
    '﻿job_position_name', 'educationaL_requirements',
    'experiencere_requirement', 'age_requirement', 
    'responsibilities.1', 'skills_required'
]
# Join columns while explicitly forcing everything to be a string and ignoring NaNs
df['resume_text'] = df[resume_cols].apply(lambda x: ' '.join(x.dropna().astype(str)), axis=1)
df['jd_text'] = df[jd_cols].apply(lambda x: ' '.join(x.dropna().astype(str)), axis=1)

In [13]:
print(df[['resume_text', 'jd_text']].head())

                                         resume_text  \
0  Big data analytics working and database wareho...
1  Fresher looking to join as a data analyst and ...
2  ['Software Development', 'Machine Learning', '...
3  To obtain a position in a fast-paced business ...
4  Professional accountant with an outstanding wo...

                                             jd_text
0  Senior Software Engineer B.Sc in Computer Scie...
1  Machine Learning (ML) Engineer M.Sc in Compute...
2  Executive/ Senior Executive- Trade Marketing, ...
3  Business Development Executive Bachelor/Honors...
4  Senior iOS Engineer Bachelor of Science (BSc) ...

In [14]:


junk_chars = r'[\[\]"\',\n\r\t]'

df['resume_text'] = df['resume_text'].str.replace(junk_chars, ' ', regex=True)
df['jd_text'] = df['jd_text'].str.replace(junk_chars, ' ', regex=True)

In [15]:
df['resume_text'] = df['resume_text'].str.lower()
df['jd_text'] = df['jd_text'].str.lower()

In [16]:
junk_words = r'\b(n/a|nan|none)\b'
df['resume_text'] = df['resume_text'].str.replace(junk_words, '', regex=True)
df['jd_text'] = df['jd_text'].str.replace(junk_words, '', regex=True)

In [17]:
df['resume_text'] = df['resume_text'].str.replace(r'\s+', ' ', regex=True).str.strip()
df['jd_text'] = df['jd_text'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [18]:
print(df[['resume_text', 'jd_text']].head())

                                         resume_text  \
0  big data analytics working and database wareho...
1  fresher looking to join as a data analyst and ...
2  software development machine learning deep lea...
3  to obtain a position in a fast-paced business ...
4  professional accountant with an outstanding wo...

                                             jd_text
0  senior software engineer b.sc in computer scie...
1  machine learning (ml) engineer m.sc in compute...
2  executive/ senior executive- trade marketing h...
3  business development executive bachelor/honors...
4  senior ios engineer bachelor of science (bsc) ...

In [19]:
keep_cols = ['resume_text', 'jd_text', 'matched_score']
df = df[keep_cols]

In [20]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9544 entries, 0 to 9543
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   resume_text    9544 non-null   object
 1   jd_text        9544 non-null   object
 2   matched_score  9544 non-null   float64
dtypes: float64(1), object(2)
memory usage: 223.8+ KB
None
                                         resume_text  \
0  big data analytics working and database wareho...
1  fresher looking to join as a data analyst and ...
2  software development machine learning deep lea...
3  to obtain a position in a fast-paced business ...
4  professional accountant with an outstanding wo...

                                             jd_text  matched_score
0  senior software engineer b.sc in computer scie...       0.850000
1  machine learning (ml) engineer m.sc in compute...       0.750000
2  executive/ senior executive- trade marketing h...       0.416667
3  business development executive bachelor/honors...       0.760000
4  senior ios engineer bachelor of science (bsc) ...       0.650000

In [21]:
df.to_csv('cleaned_resume_jd_dataset_2', index=False)